### ISSUE TITLE
[Feature Request]: support static builds

### ISSUE THREAD

**Issue by waldenn** [mlc-ai/web-llm-chat#46]
### Problem Description

I would like to a static version of the web app (if possible!).

Adding "output: export" in "next.config.mjs", complains about the header, and after removing some of those, the build still gives an error. Not sure how to fix this.

### Solution Description

Would be nice if this static build mode was supported properly, as I think this app should be able to be fully local also. Thanks for a great project!

**Comment by Neet-Nestor** [comment]
It's already supported. Just use `yarn export` instead of `yarn build`.

It may complain about the header but it won't affect the build I think.
