### ISSUE TITLE
[Feature Request]: Model Selection Filter Highlight Active Items

### ISSUE THREAD

**Issue by ColaIan** [mlc-ai/web-llm-chat#66]
### Problem Description

The filter is confusing, currently the last clicked item stays blurple, and active filters are not colored

### Solution Description

Put blurple borders when the model category is active, remove when inactive

### Alternatives Considered

N/A

### Additional Context

https://github.com/user-attachments/assets/18be19dd-b7c5-49e8-bb81-e30127619a20

**Comment by Neet-Nestor** [comment]
Thanks for reporting, will fix it soon.

**Comment by Neet-Nestor** [comment]
Fixed in d182c857b335ca4ac89b92a365bf001276804541.
<img width="669" alt="Screenshot 2024-12-10 at 12 39 41 AM" src="https://github.com/user-attachments/assets/28d941ce-d541-4a0a-869e-cb8ebbff3813">
